version: '3.9'

services:
    vue:
        container_name: pedigree_client_app
        build: ./vue
        ports:
            - "9999:8080"
        volumes:
            - ./vue/src:/vue/src
            - ./vue/package.json:/vue/package.json
